name: Backend CI - Linting & Code Quality

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  lint:
    name: Lint Backend Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (code formatter check)
        run: |
          cd backend
          black --check --diff .

      - name: Run Flake8 (linting)
        run: |
          cd backend
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run isort (import sorting check)
        run: |
          cd backend
          isort --check-only --diff .

  type-check:
    name: Type Check (mypy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mypy (type checking)
        run: |
          cd backend
          mypy app/ --ignore-missing-imports

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install bandit
        run: pip install bandit

      - name: Run Bandit (security linter)
        run: |
          cd backend
          bandit -r app/ -ll

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, type-check, security]
    if: always()

    steps:
      - name: Check all jobs status
        run: |
          echo "Lint job: ${{ needs.lint.result }}"
          echo "Type check job: ${{ needs.type-check.result }}"
          echo "Security job: ${{ needs.security.result }}"

          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.type-check.result }}" != "success" ] || \
             [ "${{ needs.security.result }}" != "success" ]; then
            echo "❌ Some CI checks failed"
            exit 1
          fi

          echo "✅ All CI checks passed"
