name: Web Frontend CI - Linting & Type Check

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/web/**'
      - '.github/workflows/ci-web.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/web/**'
      - '.github/workflows/ci-web.yml'

jobs:
  lint:
    name: Lint Web Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci

      - name: Run ESLint
        run: |
          cd apps/web
          npm run lint

      - name: Run Prettier check
        run: |
          cd apps/web
          npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css}"

  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci

      - name: Run TypeScript compiler check
        run: |
          cd apps/web
          npx tsc --noEmit

  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/web
          npm ci

      - name: Build project
        run: |
          cd apps/web
          npm run build

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, type-check, build]
    if: always()

    steps:
      - name: Check all jobs status
        run: |
          echo "Lint job: ${{ needs.lint.result }}"
          echo "Type check job: ${{ needs.type-check.result }}"
          echo "Build job: ${{ needs.build.result }}"

          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.type-check.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ]; then
            echo "❌ Some CI checks failed"
            exit 1
          fi

          echo "✅ All CI checks passed"
